# autogenerated by txs
\RSlargest#S
\RSpercentTolerance#S
\RSsmallest#S
\expandafter#S
\larger{arg1}#S
\mathlarger{arg1}#S
\mathsmaller{arg1}#S
\relscale{arg1}#S
\relsize{arg1}#S
\rs#S
\smaller{arg1}#S
\textlarger{arg1}{arg2}#S
\textscale{arg1}{arg2}#S
\textsmaller{arg1}{arg2}#S
\\larger #S
\\smaller #S
\\textlarger #S
\\textsmaller #S
\larger #S
\mathlarger #S
\mathsmaller #S
\relscale #S
\relsize #S
\smaller #S
\textlarger #S
\textscale #S
\textsmaller #S
