# autogenerated by txs
\addressSep#S
\addressskip#S
\address{arg1}#S
\begin{rSection}#S
\begin{rSubsection}#S
\end{rSection}#S
\end{rSubsection}#S
\namesize#S
\nameskip#S
\name{arg1}#S
\printaddress{arg1}#S
\printname#S
\sectionlineskip#S
\sectionskip#S
