    ------------- disabled ----------
  --  {
  --    'nvim-tree/nvim-tree.lua',
  --    enabled = false,
  --    event = "VeryLazy",
  --    config = function()
  --      require("plugin_configs.nvim-tree")
  --      require("plugin_keymaps").nvim_tree()
  --    end
  --
  --
  --  },
  --
  --  {
  --    'ggandor/leap-ast.nvim',
  --    -- right now prefer treehopper because it gives more hints
  --    config = function() require("plugin_keymaps").leap_ast() end,
  --    enabled = false,
  --
  --  },
  --  {
  --    "mfussenegger/nvim-treehopper",
  --    enabled = true,
  --    event = "VeryLazy",
  --    dependencies = "phaazon/hop.nvim",
  --    config = function() require("plugin_configs.nvim-treehopper") end,
  --  },
  --  {
  --    'altermo/nxwm',
  --    enabled = false,
  --    branch = 'x11',
  --    config = function()
  --      require('plugin_configs.nxwm')
  --    end
  --  },
  --  {
  --    -- startup screen
  --    "goolord/alpha-nvim",
  --    enabled = false,
  --    cond = require("plugin_configs.alpha-nvim.cond"),
  --    config = function()
  --      require("plugin_configs.alpha-nvim.config")
  --    end,
  --
  --  },
  --  ({
  --    "neoclide/coc.nvim",
  --    branch = "release",
  --    enabled = false,
  --    dependencies = { "neoclide/coc-snippets" },
  --    init = function()
  --      require("plugin_configs.coc")
  --    end,
  --    event = "VeryLazy",
  --  }),
  --
  --  { "tpope/vim-scriptease", enabled = false }, -- messes with s mapping of leap
  --
  --  {
  --    "josa42/nvim-gx",
  --    enabled = false,
  --    config = function()
  --      vim.keymap.set('n', 'gx', require('gx').gx)
  --    end
  --  },
  --{
  --  "bassamsdata/namu.nvim",
  --  config = function()
  --    require("plugin_configs.namu")
  --  end
  --},



  --{
  --  "Rentib/cliff.nvim",
  --  event = "VeryLazy",
  --  keys = {
  --    { '<c-j>', mode = { 'n', 'v', 'o' }, function() require("cliff").go_down() end },
  --    { '<c-k>', mode = { 'n', 'v', 'o' }, function() require("cliff").go_up() end },
  --  },
  --},
  --{
  --  's1n7ax/nvim-window-picker',
  --  name = 'window-picker',
  --  event = 'VeryLazy',
  --  version = '2.*',
  --  config = function()
  --    require("plugin_configs.window-picker")
  --  end,
  --},
  --{
  --  'jam1015/nvim_gui_termquit',
  --  dependencies = { "famiu/bufdelete.nvim" },
  --  cond = false,--function() return  (vim.g.neovide or vim.g.neovim_qt or vim.g.goneovim) end,
  --  config = function()
  --      require("nvim_gui_termquit").setup()
  --  end
  --},
  --{
  --  "ggandor/flit.nvim",
  --  enabled = false,
  --  event = "VeryLazy",
  --  --commit = "f60e4b3d49bb5a5e97cfffe66f2e671eb422078e",
  --  config = function() require("plugin_configs.flit") end,
  --  dependencies = { { 'tpope/vim-repeat' }, { 'ggandor/leap.nvim' } }
  --},
  --{
  --  -- using leap instead
  --  "ggandor/leap.nvim",
  --  enabled = false,
  --  event = "VeryLazy",
  --  --commit ="8facf2eb6a378fd7691dce8c8a7b2726823e2408",
  --  config = function()
  --    require('plugin_keymaps').leap()
  --  end
  --},
  --{
  --  "Rentib/cliff.nvim",
  --  event = "VeryLazy",
  --  keys = {
  --    { '<c-j>', mode = { 'n', 'v', 'o' }, function() require("cliff").go_down() end },
  --    { '<c-k>', mode = { 'n', 'v', 'o' }, function() require("cliff").go_up() end },
  --  },
  --},
  --{
  --  'Shatur/neovim-session-manager',
  --  enabled = false
  --},
