#!/bin/bash

Main() {
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

    local command=(
        eos_yad --title="EndeavourOS i3-wm keybindings:" --no-buttons --geometry=400x450-15-400 --list
        --column=key: --column=description: --column=command:
        "ESC" "close this app" ""
        "=" "modkey" "(set mod Mod4)"
        "+Enter" "open a terminal" ""
        "+Shift+n" "new empty workspace" ""
        "+w" "layout stacking" ""
        "+t" "layout tabbed" ""
        "+e" "toggle split layout" ""
        "+d" "app menu" ""
        "+q" "close focused app" ""
        "Print-key" "screenshot" ""
        "+Shift+e" "logout menu" ""
        "F1" "open keybinding helper" ""
        "+Shift+space" "toggle tiling / floating" ""
        "+space" "focus mode toggle" ""
        "+Shift+r" "restart i3" ""
        "+Shift+c" "reload i3 configuration" ""
        "+Ctrl+l" "focus workspace right" ""
        "+Ctrl+h" "focus workspace left" ""
        "+Ctrl+j" "focus workspace down" ""
        "+Ctrl+k" "focus workspace up" ""
        "+Tab" "switch to next workspace" ""
        "+Shift+Tab" "switch to previous workspace" ""
    )

    "${command[@]}"
}

Main "$@"
